{
 "title": "Smart Zone Ports",
 "tags": [
  "smartzone",
  "sz_subdash"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Device:",
    "query": "label_values(smartzone_system_cpu_usage{job=~\"smartzone.*\"}, instance)"
   },
   {
    "name": "port",
    "label": "Interface",
    "query": "label_values(smartzone_system_port_rxBps{job=~\"smartzone.*\"}, port)"
   }
  ]
 },
 "panels": [
  {
   "title": "$port  - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "repeat": "port",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Packets - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "repeat": "port",
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Dropped Packet - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "repeat": "port",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Total - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "repeat": "port",
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port  - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Packets - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Dropped Packet - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Total - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port  - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Packets - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Dropped Packet - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Total - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port  - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Packets - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Dropped Packet - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Total - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port  - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBps{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Packets - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxPackets{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Dropped Packet - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_port_txDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "smartzone_system_port_rxDropped{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  },
  {
   "title": "$port - Total - IN/OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "8*smartzone_system_port_txBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "in: {{port}}"
    },
    {
     "expr": "8*smartzone_system_port_rxBytes{instance=\"$instance\", port=~\"$port\"}",
     "legendFormat": "out: {{port}}"
    }
   ]
  }
 ]
}