{
 "title": "Smart Zone Controller",
 "tags": [
  "smartzone",
  "sz_subdash"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Device",
    "query": "label_values(smartzone_system_cpu_usage{job=~\"smartzone.*\"}, instance)"
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "label_values(smartzone_domain_apCount{job=~\"smartzone.*\"}, domain_name)"
   },
   {
    "name": "zone",
    "label": "Zones",
    "query": "label_values(smartzone_zone_connected_aps{job=~\"smartzone.*\"}, zone_name)"
   }
  ]
 },
 "panels": [
  { "title": "System Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 1 },
   "format": "pixel",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(smartzone_controller_ap_firmware_version{instance=\"$instance\"}) by (apVersion)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 1 },
   "format": "pixel",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(smartzone_controller_cluster_role{instance=\"$instance\"}) by (serialNumber)"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_cpu_usage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_memory_usage{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "smartzone_system_disk_free{instance=\"$instance\"}",
     "legendFormat": "free"
    },
    {
     "expr": "smartzone_system_disk_size{instance=\"$instance\"}",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "License", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(smartzone_license_description{instance=\"$instance\"}) by (license_name, description)"
    },
    {
     "expr": "sum(smartzone_license_count{instance=\"$instance\"}) by (license_name)"
    },
    {
     "expr": "sum(smartzone_license_createTime{instance=\"$instance\"}) by (license_name, createTime)"
    },
    {
     "expr": "sum(smartzone_license_expireDate{instance=\"$instance\"}) by (license_name, expireDate)"
    }
   ]
  },
  { "title": "Domain - $domain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }, "repeat": "domain" },
  {
   "title": "APs Number",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "repeat": "domain",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "smartzone_domain_apCount{instance=\"$instance\", domain_name=~\"$domain\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(smartzone_domain_subDomainCount{instance=\"$instance\", domain_name=~\"$domain\"}) by (domain_name)"
    },
    {
     "expr": "sum(smartzone_domain_type{instance=\"$instance\", domain_name=~\"$domain\"}) by (domain_name, domainType)"
    },
    {
     "expr": "sum(smartzone_domain_zoneCount{instance=\"$instance\", domain_name=~\"$domain\"}) by (domain_name, domainType)"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "repeat": "zone" },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 30 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 37 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 44 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 44 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 44 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 44 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 46 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 51 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 51 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 51 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 51 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 53 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 58 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 58 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 58 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 58 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 60 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 65 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 65 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 65 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 65 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 67 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 72 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 72 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 72 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 72 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 74 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 79 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 79 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 79 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 79 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 81 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 86 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 86 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 86 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 86 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 88 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  { "title": "Zone: $zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 93 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_connected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 93 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_disconnected_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 93 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_discovery_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 93 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_aps{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 95 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "smartzone_zone_total_connected_clients{instance=\"$instance\", zone_name=~\"$zone\"}"
    }
   ]
  }
 ]
}